### ISSUE TITLE
Type of electric mechanical lock

### ISSUE THREAD

**Issue by falanster** [torehc/carontepass-v2#11]
I've just started to use your solution for door in our maker space. Market is full filled with different ready to use proprietary solutions. Could you recommend any electric mechanical locks?

**Comment by torehc** [comment]
The good thing about this solution is that with the relay you can change the lock whenever you want, it is an independent system.
You can buy the cheapest lock that works the same, is to activate a mechanism.
We use one of this style: [electric lock door](https://www.aliexpress.com/item/Electric-Strike-Door-Lock-Electronic-For-Access-Control-System-New-Fail-Secure-Stainless-Door-12V-DC/32910427672.html)
