### ISSUE TITLE
Access to control 

### ISSUE THREAD

**Issue by moos3** [torehc/carontepass-v2#4]
Question, How does the multiple devices work? Can i do the following:

Sue has access to Door 1, 2 but not door 3
John has access to All Doors
Bob only has access to Door 1
Sally has access to Door 2 for the next 24 hours

Can this kind of access be done with this system?

**Comment by torehc** [comment]
Multiple access support does not include access to different sites in space.
That is, it is designed to have multiple access doors to space, but once you are inside it does not differentiate the rooms by types of access.

I encourage you to test the system so you will see the advantages you have and knowing how it works you will see that the implementation you are talking about is not complicated to implement.

**Comment by moos3** [comment]
Ok thanks. We have multiple levels and offices in the space. We are hoping to use this as a base and i'll add that functionality and contrib it back to you.
